[build]
builder = "dockerfile"

[deploy]
startCommand = "python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300

[experimental]
incrementalBuildPaths = ["./"] 